// settings:
:toc: macro
:toc-title: Sommaire
:toclevels: 2
:numbered:
:sectnumlevels: 2

ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// variables:

:uri-org: https://github.com/jprivet-dev
:uri-repo: {uri-org}/symfony-tdd

:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site,env-yard[]
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
endif::[]

:uri-license: {uri-rel-file-base}LICENSE

:BACK_TO_TOP_TARGET: top-target
:BACK_TO_TOP_LABEL: ⬆ Retour au sommaire
:BACK_TO_TOP: <<{BACK_TO_TOP_TARGET},{BACK_TO_TOP_LABEL}>>

[#{BACK_TO_TOP_TARGET}]
= Symfony 4 & TDD - PHPUnit - Vue.js & Jest - (dockerized workshop)

image:https://img.shields.io/badge/branch-master-green["master", link="https://github.com/jprivet-dev/symfony-tdd"]
image:https://travis-ci.org/jprivet-dev/symfony-tdd.svg?branch=master["Build Status", link="https://travis-ci.org/jprivet-dev/symfony-tdd"]
image:https://coveralls.io/repos/github/jprivet-dev/symfony-tdd/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/github/jprivet-dev/symfony-tdd?branch=master"]
image:https://api.codacy.com/project/badge/Grade/d83935eebccc4610870a0b52039914f3?branch=master["Codacy code quality", link="https://www.codacy.com/manual/jprivet-dev/symfony-tdd?utm_source=github.com&utm_medium=referral&utm_content=jprivet-dev/symfony-tdd&utm_campaign=Badge_Grade"]
 +
image:https://img.shields.io/badge/branch-dev-green["dev", link="https://github.com/jprivet-dev/symfony-tdd/tree/dev"]
image:https://travis-ci.org/jprivet-dev/symfony-tdd.svg?branch=dev["Build Status", link="https://travis-ci.org/jprivet-dev/symfony-tdd"]
image:https://coveralls.io/repos/github/jprivet-dev/symfony-tdd/badge.svg?branch=dev["Coverage Status", link="https://coveralls.io/github/jprivet-dev/symfony-tdd?branch=dev"]
image:https://api.codacy.com/project/badge/Grade/d83935eebccc4610870a0b52039914f3?branch=dev["Codacy code quality", link="https://www.codacy.com/manual/jprivet-dev/symfony-tdd?utm_source=github.com&utm_medium=referral&utm_content=jprivet-dev/symfony-tdd&utm_campaign=Badge_Grade"]

image:https://img.shields.io/badge/makefile-yes-blue[Makefile]
image:https://img.shields.io/github/license/jprivet-dev/symfony-tdd[GitHub]

toc::[]

== Présentation

=== L'atelier

Ce dépôt *Git*  fraîchement créé est un atelier où je concentre, teste et partage des cas pratiques rencontrés (projets clients, R&D, ...)
autour des *tests automatiques PHP & JavaScript (Vue.js)*, du *TDD* (Test-Driven Development) et du framework *Symfony*.

J'ai démarré cet atelier à partir du dépôt https://github.com/dunglas/symfony-docker de https://dunglas.fr/[Kevin Dunglas].

{BACK_TO_TOP}

=== L'avancé des sujets

*Les titres de la doc sont tagués* de la façon suivante :

. [ ] A faire
. [!] En cours
. [x] Fait

{BACK_TO_TOP}

== Prérequis technique : avoir *Docker CE* et *Docker Compose* installés

. https://docs.docker.com/install/
. https://docs.docker.com/compose/install/

{BACK_TO_TOP}

== Installer le projet

=== Cloner

```
$ git clone git@github.com:jprivet-dev/symfony-tdd.git
```

{BACK_TO_TOP}

=== Installer

```
$ cd symfony-tdd
$ make install
...
...
...
READY!
  Website:    http://localhost
  API:        http://localhost/api
  phpMyAdmin: http://localhost:8088

APP_ENV=dev
```

{BACK_TO_TOP}

=== Accéder au site

A la fin de l'installation, vous pourrez avoir accès aux *URLs suivantes* :

. Site web : https://localhost
. API : https://localhost/api
. phpMyAdmin: http://localhost:8088

{BACK_TO_TOP}

== Le *Makefile* du projet [[makefile]]

=== Les commandes disponibles

Si vous avez un outil du type https://www.gnu.org/software/make/[GNU Make] disponible sur votre poste,
vous pouvez acceder à toutes les commandes du fichier {uri-rel-file-base}Makefile[] :

```
$ make
```

Liste des commandes disponibles :

// >>> block_makefile
```

PROJECT
  start                          Project: Start the current project.
  start.one                      Project: Stop all containers & start the current project.
  stop                           Project: Stop the current project.
  sh                             Project: app sh access.

  install                        Project: Install all (dependencies, data, assets, ...) according to the current environment (APP_ENV).
  install.dev                    Project: Force the installation for the "dev" environment.
  install.prod                   Project: Force the installation for the "prod" environment.

  dependencies                   Project: Install the dependencies (only if there have been changes).
  assets                         Project: Generate all assets according to the current environment (APP_ENV).
  assets.dev                     Project: Generate all assets (webpack Encore, ...) for the "dev" environment.
  assets.prod                    Project: Generate all assets (webpack Encore, ...) for the "prod" environment.
  data                           Project: Install the data (db).
  fixtures                       Project: Load all fixtures.

  check                          Project: Launch of install / Composer, Security and DB validations / Tests
  tests                          Project: Launch all tests (PHPUnit, Jest, ...).
  coverage                       Project: Generate & open all code coverage reports.

  cc                             Project: Clear all caches.
  clean                          Project: [PROMPT yN] Remove build, vendor & node_modules folders.

ENVIRONMENT
  env.app                        Environment: Print current APP_ENV in Makefile.
  env.local.dev                  Environment: Alias of `env.local.clean`.
  env.local.prod                 Environment: [PROMPT yN] Copy '.env.local.prod.dist' into '.env.local' (APP_ENV=prod)
  env.local.test                 Environment: [PROMPT yN] Copy '.env.local.test.dist' into '.env.local' (APP_ENV=test)
  env.local.clean                Environment: [PROMPT yN] Remove '.env.local' and use default vars & environment of '.env' (APP_ENV=dev)

COMPOSER
  composer.install               Composer: Read the composer.json/composer.lock file from the current directory, resolve the dependencies, and install them into vendor.
  composer.install.prod          Composer: Idem `composer.install` without dev elements.
  composer.update                Composer: Get the latest versions of the dependencies and update the composer.lock file.
  composer.licenses              Composer: List the name, version and license of every package installed.
  composer.validate              Composer: Check if your composer.json is valid. | https://getcomposer.org/doc/03-cli.md#validate
  composer.dumpenv.prod          Composer: Dump .env files for "prod".

YARN
  yarn.install                   Yarn: Install all dependencies.
  yarn.upgrade                   Yarn: Upgrade packages to their latest version based on the specified range.
  yarn.test                      Yarn: Launch test package script (Jest).

ENCORE
  encore.compile                 Webpack Encore: Compile assets once.
  encore.watch                   Webpack Encore: Recompile assets automatically when files change.
  encore.deploy                  Webpack Encore: On deploy, create a production build.

SYMFONY
  symfony.cc                     Symfony: Clear cache (current env).
  symfony.ccp                    Symfony: Clear cache (prod).
  symfony.cchard                 Symfony: Remove all in `var/cache` folder.
  symfony.routes                 Symfony: Display current routes.

  symfony.about                  Symfony: Display information about the current project (Symfony, Kernel, PHP, Environment, ...).
  symfony.env.vars               Symfony: List defined environment variables. | https://symfony.com/doc/current/configuration.html#configuration-based-on-environment-variables

  symfony.security.check         Symfony: Check security of your dependencies. | https://github.com/sensiolabs/security-checker

ALICE BUNDLE
  alice.fixtures.load            AliceBundle: load fixtures.

PHPUNIT
  phpunit                        PHPUnit: Launch all tests (unit, functional, ...).
  phpunit.coverage               PHPUnit: Generate code coverage report in HTML format.
  phpunit.coverage.clover        PHPUnit: Generate code clover style coverage report.
  phpunit.coverage.open          PHPUnit: Open code coverage report.

  phpunit.unit                   PHPUnit: Launch unit tests.
  phpunit.unit.coverage          PHPUnit: Generate code coverage report in HTML format for unit tests.
  phpunit.functional             PHPUnit: Launch functional tests.
  phpunit.functional.coverage    PHPUnit: Generate code coverage report in HTML format for functional tests.

  phpunit.watch                  PHPUnit Watcher: Rerun automatically tests whenever you change some code. | https://github.com/spatie/phpunit-watcher
  phpunit.watch.unit             PHPUnit Watcher: Rerun only unit tests.
  phpunit.watch.functional       PHPUnit Watcher: Rerun only functional tests.

XDEBUG
  xdebug.on                      Xdebug: Enable the module.
  xdebug.off                     Xdebug: Disable the module.

QUALITY ASSURANCE - STATIC ANALYZERS
  qa.phpmetrics                  PHPMetrics: Provide tons of metric (complexity / volume / object oriented / maintainability). | http://www.phpmetrics.org
  qa.codesniffer                 PHP_CodeSniffer: Tokenize PHP, JavaScript and CSS files and detect violations... | https://github.com/squizlabs/PHP_CodeSniffer
  qa.codesniffer.diff            PHP_CodeSniffer: Printing a diff report
  qa.codesniffer.fix             PHP_CodeSniffer: Fixing errors automatically
  qa.messdetector                PHP Mess Detector: Scan PHP source code and look for potential problems... | http://phpmd.org/

DATABASE
  db.create                      Database: Creates the configured database & Executes the SQL needed to generate the database schema.
  db.create.force                Database: Drop & create.
  db.drop                        Database: Drop.
  db.update                      Database: Generate & execute a Doctrine migration.

  db.validate                    Database: Validate the mapping files.
  db.entities                    Database: List mapped entities.
  db.bash                        Database: Bash access.
  db.mysql                       Database: MySQL access (mysql> ...).

DOCTRINE
  doctrine.database.create       Doctrine: Create the configured database.
  doctrine.database.create.force Doctrine: Drop & create the configured database.
  doctrine.database.drop         Doctrine: Drop the configured database.

  doctrine.schema.validate       Doctrine: Validate the mapping files.
  doctrine.mapping.info          Doctrine: List mapped entities.

  doctrine.migrations.diff       Doctrine: Generate a migration by comparing your current database to your mapping information.
  doctrine.migrations.migrate    Doctrine: Execute a migration to the latest available version.
  doctrine.migrations.migrate.nointeract Doctrine: Execute a migration to the latest available version (no interaction).

DOCKER
  docker.start                   Docker: Build, (re)create, start, and attache to containers for a service (detached mode). | https://docs.docker.com/compose/reference/up/
  docker.start.one               Docker: Stop all projects running containers & Start current project.
  docker.build                   Docker: Same `docker.start` command + build images before starting containers (detached mode). | https://docs.docker.com/compose/reference/up/
  docker.build.force             Docker: Stop, remove & rebuild current containers.
  docker.stop                    Docker: Stop running containers without removing them. | https://docs.docker.com/compose/reference/stop/
  docker.stop.all                Docker: Stop all projects running containers without removing them. | https://docs.docker.com/compose/reference/stop/
  docker.down                    Docker: [PROMPT yN] Stop containers and remove containers, networks, volumes, and images created by up. | https://docs.docker.com/compose/reference/down/

  docker.list                    Docker: List containers. | https://docs.docker.com/engine/reference/commandline/ps/
  docker.list.stopped            Docker: List all stopped containers.
  docker.remove                  Docker: [PROMPT yN] Stop & Remove service containers (only current project). | https://docs.docker.com/compose/reference/rm/
  docker.remove.all              Docker: [PROMPT yN] Remove all stopped service containers. | https://docs.docker.com/compose/reference/rm/
  docker.images                  Docker: List images. | https://docs.docker.com/engine/reference/commandline/images/
  docker.images.remove.all       Docker: [PROMPT yN] Remove all unused images (for all projects!).
  docker.clean                   Docker: [PROMPT yN] Remove unused data. | https://docs.docker.com/engine/reference/commandline/system_prune/

  docker.env                     Docker: Show environment variables.
  docker.ip                      Docker: Get ip Gateway.
  docker.ip.all                  Docker: List all containers ip.
  docker.networks                Docker: list networks. | https://docs.docker.com/engine/reference/commandline/network/
  docker.logs                    Docker: Show logs.

UTIL
  util.chown.fix                 Util (Permissions): Editing permissions on Linux. | https://github.com/dunglas/symfony-docker#editing-permissions-on-linux
  util.readme.update             Util (Readme.adoc): Retrieve and insert the latest makefile commands & aliases in the Readme.adoc.
  util.php.strict                Util (PHP): Insert `<?php declare(strict_types=1);` instead of `<?php` in all PHP files in src/ & tests/ folders.
  util.ide.phpstorm.templates    Util (PHPStorm): Copy templates from .ide/PHPStorm/fileTemplates folder in .idea/fileTemplates folder. | https://www.jetbrains.com/help/phpstorm/using-file-and-code-templates.html

MAKEFILE
  help                           Makefile: Print self-documented Makefile.
  list                           Makefile: List all included files.
```
// <<< block_makefile

{BACK_TO_TOP}

=== Ressources

La construction du fichier {uri-rel-file-base}Makefile[] de ce repo est grandement inspirée des ressources suivantes :

. https://blog.theodo.fr/2018/05/why-you-need-a-makefile-on-your-project/
. https://github.com/mykiwi/symfony-bootstrapped/blob/master/Makefile
. https://github.com/Elao/symfony-standard/blob/master/Makefile
. https://github.com/Elao/tricot/blob/master/Makefile
. https://github.com/cleverage/eav-manager-starter-kit/blob/master/Makefile
. https://github.com/torvalds/linux/blob/master/Makefile

{BACK_TO_TOP}

== Les *alias* du projet [[aliases]]

Le fichier {uri-rel-file-base}.bash_aliases[] propose quelques *raccourcis* (`php`, `composer`, `yarn`, `sf`, ...) :

// >>> block_aliases
```

alias reload=". .bash_aliases"

alias app="docker-compose exec app"
alias composer="app composer"
alias yarn="app yarn"
alias php="app php"
alias phpunit="app ./vendor/bin/simple-phpunit"
alias phpunit-watch="app ./vendor/bin/phpunit-watcher watch"
alias symfony="php bin/console"

alias cc="symfony cache:clear"
alias ccp="symfony cache:clear --env=prod"

alias tests="phpunit --stop-on-error --stop-on-failure --stop-on-warning"
alias tests-no-stop="phpunit"
alias tests-coverage="phpunit --coverage-html build/phpunit/coverage"
alias tests-watch="phpunit-watch"
alias open-coverage="gio open build/phpunit/coverage/index.html"

alias m="make"
alias sf="symfony"
alias t="tests"
alias tnostop="tests-no-stop"
alias tc="
tests-coverage;
open-coverage;
"
alias tw="tests-watch"
alias ut="make unit-tests"
alias ft="make functional-tests"

alias chownfix="docker-compose run --rm app chown -R $(id -u):$(id -g) ."

alias project-install="
docker-compose up --remove-orphans -d;
docker-compose exec app composer install --verbose;
docker-compose exec app yarn install;
docker-compose exec app php bin/console doctrine:database:drop --if-exists --force;
docker-compose exec app php bin/console doctrine:database:create;
docker-compose exec app php bin/console doctrine:schema:create;
"
```
// <<< block_aliases

Charger les *alias* du projet :

```
$ . .bash_aliases
```

IMPORTANT: Le fichier {uri-rel-file-base}.bash_aliases[] ne peut être chargé automatiquement à la commande `start` du {uri-rel-file-base}Makefile[].

{BACK_TO_TOP}

== *PHPUnit* : gérer les tests automatiques PHP [[phpunit]]

=== Lancer les tests PHP

Le projet utilise le *PHPUnit Bridge* de *Symfony* (https://symfony.com/doc/current/testing.html).

Pour lancer les tests, chargez d'abord les fixtures :

```
$ make fixtures
```

Exécutez ensuite les tests :

```
$ make phpunit

Xdebug OFF
docker-compose exec app ./vendor/bin/simple-phpunit
stty: standard input
PHPUnit 8.4.3 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

Testing
..............................................                    46 / 46 (100%)

Time: 2.88 seconds, Memory: 34.25 MB

OK (46 tests, 97 assertions)
```

TIP: La commande `$ make tests` charge les fixtures et lance tous les tests disponibles (PHPUnit, Jest, ...).

{BACK_TO_TOP}

=== *PHPUnit Watcher* : relance automatiquement des tests après modification d'un fichier

Le projet utilise *PHPUnit Watcher* (https://github.com/spatie/phpunit-watcher) que vous pouvez lancer avec la commande suivante :

```
$ make phpunit.watch
```

{BACK_TO_TOP}

=== *Xdebug & Performance* : activation et désactivation à chaud du module

WARNING: *Xdebug* est nécessaire pour générer la couverture de code, mais *augmente considérablement (x10)* le temps d'exécution des tests.

Exécution *avec Xdebug* => *1.52 secondes* :

```
$ docker-compose exec app ./vendor/bin/simple-phpunit
stty: standard input
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

Testing
................................                                  32 / 32 (100%)

Time: 1.52 seconds, Memory: 24.00 MB

OK (32 tests, 74 assertions)
```

Exécution *sans Xdebug* => *153 ms* :

```
$ docker-compose exec app ./vendor/bin/simple-phpunit
stty: standard input
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

Testing
................................                                  32 / 32 (100%)

Time: 153 ms, Memory: 18.00 MB

OK (32 tests, 74 assertions)
```

[TIP]
====
*Xdebug* peut être activé et désactivé à chaud avec les commandes suivantes :

```
$ make xdebug.on
$ make xdebug.off
```
====

*Xdebug* est automatiquement désactivé pour les tests qui ne nécessitent pas de couverture de code et réactivé dans le cas contraire.

Exemples de commandes avec *Xdebug désactivé automatiquement* :

```
$ make phpunit
$ make phpunit.unit
$ make phpunit.functional
$ make phpunit.watch
...
```
Exemples de commandes *avec Xdebug activé automatiquement* :

```
$ make phpunit.coverage
$ make phpunit.coverage.clover
$ make phpunit.unit.coverage
$ make phpunit.functional.coverage
...
```

{BACK_TO_TOP}

== *Vue.js* : gérer les tests automatiques JS avec *Jest*

=== Lancer les tests JS

Le projet utilise *Jest* avec la librarie *Vue Test Utils* (https://vue-test-utils.vuejs.org/).

Lancez les tests avec la commande suivante :

```
$ make yarn.test

docker-compose exec app yarn test
yarn run v1.16.0
$ jest
 PASS  assets/vue-test-utils/counter.spec.js
  Counter
    ✓ renders the correct markup (4ms)
    ✓ has a button (8ms)
    ✓ button should increment the count (4ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.44s
Ran all test suites.
Done in 2.29s.
```

TIP: La commande `$ make tests` charge les fixtures et lance tous les tests disponibles (PHPUnit, Jest, ...).

=== Ressources

. https://vue-test-utils.vuejs.org/
. https://jestjs.io/
. Voir aussi dans cette doc : <<creer-tester-composant-vue-js>>

{BACK_TO_TOP}

== Sujets traités

=== [x] *Fibonacci* : 4 implémentations, 1 seul test

==== Principe

Le principe est de montrer que *4 implémentations différentes* d'une même fonctionnalité peuvent passer
correctement le *même test unitaire*.

Ce premier cas simple permet d'illustrer ce que permettent les tests automatiques : *garantir le code*.

*Qu'importe la stratégie d'implémentation choisie* par le développeur (en fonction du contexte, de ses facilités, du temps qui lui ait imparti, ...),
ce dernier peut garantir au client que son implémentation *répond bien aux besoins dans le scope testé*,
et que la fonctionnalité *réagit bien dans les cas limites retenus*.

==== Exemples

Pour une application de Planning Poker, nous avons besoins d'une méthode qui puisse nous retourner
les 12 premiers termes de la suite de Fibonacci.

Ces termes (1, 2, 3, 5, ..., 55, 89, 144) seront les valeurs de nos cartes agiles.

==== Fichiers

. {uri-rel-file-base}src/Util/Example/Fibonacci01.php[]
. {uri-rel-file-base}src/Util/Example/Fibonacci02.php[]
. {uri-rel-file-base}src/Util/Example/Fibonacci03.php[]
. {uri-rel-file-base}src/Util/Example/Fibonacci04.php[]

==== Tests

. {uri-rel-file-base}tests/Unit/Util/Example/FibonacciTest.php[]

==== Ressources

. https://rosettacode.org/wiki/Fibonacci_sequence#PHP
. https://en.wikibooks.org/wiki/Algorithm_Implementation/Mathematics/Fibonacci_Number_Program#PHP
. https://en.wikipedia.org/wiki/Fibonacci_number
. http://www.codecodex.com/wiki/Calculate_the_Fibonacci_sequence#PHP

{BACK_TO_TOP}

=== [x] Injecter un *repository* au lieu de *l'entity manager* [[injecter-repository]]

==== Principe

Au lieu d'injecter dans un premier temps *l'entity manager* pour récupérer dans un deuxième temps les *repositories* dont nous avons besoin,
nous pouvons injecter directement les *repositories* concernés.

==== Exemple

Pour récupérer et traiter les news enregistrées en base de données,
le `NewsService.php` de l'exemple suivant importe et utilise `NewsRepository.php`.

==== Fichiers

. {uri-rel-file-base}src/Controller/NewsController.php[]
. {uri-rel-file-base}src/Service/NewsService.php[]
. {uri-rel-file-base}src/Repository/NewsRepository.php[]

==== Tests

. {uri-rel-file-base}tests/Unit/Service/NewsServiceTest.php[]
. {uri-rel-file-base}tests/Functional/Controller/NewsControllerTest.php[]

==== Ressources

. https://matthiasnoback.nl/2014/05/inject-a-repository-instead-of-an-entity-manager/

{BACK_TO_TOP}

=== [x] Créer et tester un *repository*

==== Principe

Le principe est de pouvoir *vérifier les requêtes d'un repository*,
en les testant directement sur la base de données.

==== Exemple

Le repository `NewsRepository` permet de traiter des news. Nous voulons vérifier les points suivants :

. Récupérer *toutes les news*.
. Récupérer uniquement celles qui sont *publiées*.
. Récupérer *par son slug* une news publiée.
. Retourner une valeur null si le *slug est inconnu*, ou si la *news n'est pas publiée*.

TIP: Nous devons injecter des fixtures dans la base de données pour réaliser ces tests. Voir <<phpunit>>.

==== Fichiers

. {uri-rel-file-base}src/Repository/NewsRepository.php[]

==== Tests

. {uri-rel-file-base}tests/Functional/Repository/NewsRepositoryTest.php[]

==== Resources

. https://symfony.com/doc/current/testing/database.html#functional-testing-of-a-doctrine-repository
. https://matthiasnoback.nl/2018/09/test-driving-repository-classes-part-1-queries/
. https://matthiasnoback.nl/2018/10/test-driving-repository-classes-part-2-storing-and-retrieving-entities/

{BACK_TO_TOP}

=== [x] Créer et tester une *classe abstraite*

==== Principe

Le principe est de pouvoir tester unitairement les *méthodes concrètes* d'une classe abstraite.

==== Exemples

Le premier exemple est réalisé avec une classe abstraite très simple `AbstractClass`,
pour *présenter 3 méthodes de tests* élémentaires :

. Avec `getMockForAbstractClass()`.
. Avec une classe anonyme `new class()`.
. Avec une simple classe `Dummy`.

Le deuxième exemple est réalisé avec la classe abstraite `AbstractRepository`, utiliser dans <<injecter-repository>>.

==== Fichiers

. {uri-rel-file-base}src/Util/Example/AbstractClass.php[]
. {uri-rel-file-base}src/Repository/AbstractRepository.php[]

==== Tests

. {uri-rel-file-base}tests/Unit/Util/Example/AbstractClassTest.php[]
. {uri-rel-file-base}tests/Unit/Repository/AbstractRepositoryTest.php[]

==== Ressources

. https://phpunit.readthedocs.io/en/8.4/test-doubles.html#mocking-traits-and-abstract-classes
. https://mnapoli.fr/anonymous-classes-in-tests/
. https://www.php.net/manual/en/language.oop5.abstract.php

{BACK_TO_TOP}

=== [!] Créer et tester un *custom validator*

==== Principe

Le principe est de gérer et de tester facilement *tous les cas limites* auxquels pourrait-être
exposé notre *custom validator*.

==== Exemple

[ WIP ]

==== Fichiers

. {uri-rel-file-base}src/Validator/Constraints/Reference.php[]
. {uri-rel-file-base}src/Validator/Constraints/ReferenceValidator.php[]

==== Tests

. {uri-rel-file-base}tests/Unit/Validator/Constraints/ReferenceValidatorTest.php[]

==== Ressources

. https://symfony.com/doc/current/validation/custom_constraint.html
. https://github.com/symfony/validator/blob/master/Test/ConstraintValidatorTestCase.php
. https://github.com/symfony/validator/blob/master/Tests/Constraints/EmailValidatorTest.php

{BACK_TO_TOP}

=== [ ] Créer et tester un *custom type*

{BACK_TO_TOP}

=== [ ] Créer et tester une *fonction Twig*

{BACK_TO_TOP}

=== [!] Créer un *smoke testing*

==== Principe

Le principe de ce premier niveau de test fonctionnel est *d'appeler simplement chaque page* de l'application
pour vérifier *qu'aucune d'entre elles ne retournent d'erreur*.

==== Exemple

[ WIP ]

==== Tests

. {uri-rel-file-base}tests/Functional/SmokeTest.php[]

==== Ressources

. https://symfony.com/doc/current/best_practices.html

{BACK_TO_TOP}

=== [ ] Créer, dispatcher et tester un *event*

{BACK_TO_TOP}

=== [ ] Mocker le *temps*

{BACK_TO_TOP}

=== [ ] Créer et tester une *commande Symfony*

{BACK_TO_TOP}

=== [ ] Créer et tester une *requête ajax*

{BACK_TO_TOP}

=== [ ] Travailler avec le *workflow component*

{BACK_TO_TOP}

=== [ ] Travailler avec le *process bundle*

{BACK_TO_TOP}

=== [ ] Travailler avec des *collections d'objets typés*

{BACK_TO_TOP}

=== [ ] La performance avec *Doctrine*

{BACK_TO_TOP}

=== [ ] Créer et tester un *trait*

{BACK_TO_TOP}

=== [ ] Créer et tester des *éléments asynchrones PHP*

{BACK_TO_TOP}

=== [x] *Symfony Panther* : les bases (Vue.js, screenshots, ...) [[panther-bases]]

==== Principe

Le principe est de pouvoir tester fonctionnellement une *page qui interprète du JavaScript*.

==== Exemple

Nous testons fonctionnellement une page qui affiche une news, dont les commentaires
sont récupérés et affichés dynamiquement avec un *composant Vue.js*.

NOTE: Retrouvez les screenshots réalisés automatiquement par ces tests dans le dossier `build/tests/screenshots`.

==== Fichiers

. {uri-rel-file-base}src/Controller/NewsController.php[]
. {uri-rel-file-base}src/Service/NewsService.php[]
. {uri-rel-file-base}src/Repository/NewsRepository.php[]
. {uri-rel-file-base}assets/comments/CommentsComponent.vue[]
. {uri-rel-file-base}templates/news/news-item.html.twig[]

==== Tests

. {uri-rel-file-base}tests/Functional/Controller/NewsControllerTest.php[]

==== Ressources

. https://symfony.com/blog/introducing-symfony-panther-a-browser-testing-and-web-scrapping-library-for-php
. https://github.com/symfony/panther

==== Autres informations

[TIP]
====
*Docker* : Bien intégrer le binaire `chromedriver` avec une image `alpine`. Voir :

. https://github.com/symfony/panther#docker-integration
====

[WARNING]
====
*Panther* ne permet pas de générer une *couverture de code* pour le moment. Voir :

. https://github.com/symfony/panther/issues/8
. https://github.com/jprivet-dev/symfony-tdd/issues/2
. Voir aussi dans la doc <<panther-code-coverage>>
====

{BACK_TO_TOP}

=== [!] Créer et tester un *composant Vue.js* avec *Jest* [[creer-tester-composant-vue-js]]

==== Principe

Le principe est de pouvoir *tester les composants Vue.js* indépendamment de leur usage dans les pages générées avec *Symfony & Twig*.

==== Exemples

Le premier exemple est une *intégration simple* de https://github.com/vuejs/vue-test-utils-getting-started
pour établir une base.

Le deuxième exemple est une *extension des tests PHP réalisés avec Panther* dans https://symfony.com/blog/introducing-symfony-panther-a-browser-testing-and-web-scrapping-library-for-php
(Voir aussi dans la doc <<panther-bases>>) : nous utilisons en complément les *outils JavaScript dédiés aux tests des composants Vue.js*.

==== Fichiers

. {uri-rel-file-base}assets/vue-test-utils/counter.js[]
. {uri-rel-file-base}assets/comments/CommentsComponent.vue[]

==== Tests

. {uri-rel-file-base}assets/vue-test-utils/counter.spec.js[]
. {uri-rel-file-base}assets/comments/CommentsComponent.spec.js[]

==== Ressources

. https://github.com/vuejs/vue-test-utils
. https://github.com/vuejs/vue-test-utils-getting-started
. https://jestjs.io/
. https://vue-test-utils.vuejs.org/
. https://vue-test-utils.vuejs.org/guides/choosing-a-test-runner.html
. https://vue-test-utils.vuejs.org/guides/testing-single-file-components-with-jest.html
. https://www.npmjs.com/package/jest-fetch-mock
. https://github.com/facebook/jest/issues/2071

{BACK_TO_TOP}

== Tips

=== [!] *Makefile* : en local, utiliser les fichiers *.env* de Symfony

==== Récapitulatif

[%header]
|===
| File | Scope | Environment | Commited
a|`.env` | all machines | all | yes
a|`.env.local` | machine-specific | all | should not be committed
a|`.env.<env>` | all machines | <env> | yes
a|`.env.<env>.local` | machine-specific | <env> | should not be committed
|===

==== Exemple

Structuration du fichier {uri-rel-file-base}Makefile[] :

```make
SHELL:=/bin/bash

-include .env                               # (1)
-include .env.local
-include .env.$(APP_ENV)                    # (2)
-include .env.$(APP_ENV).local

MAKEFILES = .mk/*.mk
include $(sort $(wildcard $(MAKEFILES)))    # (3)
```
<1> Importation du fichier `.env` (s'il existe).
<2> La variable `APP_ENV` provient du fichier `.env` ou `.env.local`.
<3> Importation par ordre alphabétique de tous les fichiers `.mk/*.mk`.

==== Fichiers

. {uri-rel-file-base}Makefile[]
. {uri-rel-file-base}/.mk[]

==== Resources

. https://www.gnu.org/software/make/manual/html_node/Environment.html
. https://github.com/symfony/recipes/issues/18
. https://symfony.com/doc/current/configuration.html#managing-multiple-env-files
. https://symfony.com/doc/current/configuration.html#configuring-environment-variables-in-production
. https://symfony.com/blog/new-in-symfony-4-2-define-env-vars-per-environment
. https://symfony.com/doc/current/deployment.html

{BACK_TO_TOP}

=== [x] *Makefile* : *script* d'attente de disponibilité de la base de données

==== Problématique rencontrée

Après avoir démarré les conteneurs avec, par exemple, `$ make install` :

```
Starting symfony_tdd_db_service    ... done
Starting symfony_tdd_app_service ... done
Starting symfony_tdd_nginx_service      ... done
Starting symfony_tdd_phpmyadmin_service ... done
Starting symfony_tdd_h2_proxy_service   ... done
```

Vous pouvez avoir, tout juste après, *l'erreur suivante* qui s'affiche au moment de la création de la base :

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

C'est une erreur qui apparait, en particulier, à la toute première installation et qui vous stoppera toute la procédure :
le `symfony_tdd_db_service` est bien `done`, *mais l'initialisation de `MySQL` n'est qu'en à lui pas encore finie*.

{BACK_TO_TOP}

==== Solution

C'est pour cela qu'il existe la commande `db.wait` suivante :

```
PHONY: db.wait
db.wait: # Database: Wait database...
	@$(PHP) -r 'echo "\e[0;43mWait database $(DATABASE_HOST):$(DATABASE_PORT)...\e[0m\n"; \
	set_time_limit(15); for(;;) { if(@fsockopen($(DATABASE_HOST), $(DATABASE_PORT))) { break; }}; echo "\e[0;42mDatabase ready!\e[0m\n";'
```

Cette commande peut être *couplée à toutes les commandes Makefile ayant une action avec la base*.
Comme dans le cas suivant par exemple, où l'on attend que la base soit disponible avant
de vouloir s'y connecter avec le terminal :

```
PHONY: db.mysql
db.mysql: db.wait ## Database: MySQL access (mysql> ...).
	$(EXEC_DB) bash -c "mysql -u $(DATABASE_USER) $(DATABASE_NAME)"
```

{BACK_TO_TOP}

=== [ ] *Tests unitaires* : utiliser les *yield*

{BACK_TO_TOP}

=== [!] *Contrôleurs* : est-ce pertinent de les *tester unitairement* ?

==== Principe

Un contrôleur est à la base *une simple classe connectée au routeur de Symfony*.

Techniquement il est tout à faire *possible de tester unitairement* cette classe comme les autres (services, repositories, validateur, ...),
*mais est-ce pour autant pertinent de le faire ?*

==== Fichier

. {uri-rel-file-base}src/Controller/NewsController.php[]

==== Test

. {uri-rel-file-base}tests/Unit/Controller/NewsControllerTest.php[]

==== Ressources

. https://matthiasnoback.nl/2012/06/symfony2-testing-your-controllers/
. https://softwareengineering.stackexchange.com/questions/338420/why-would-you-write-unit-tests-for-controllers
. https://symfony.com/doc/current/create_framework/unit_testing.html
. https://docs.microsoft.com/fr-fr/aspnet/core/mvc/controllers/testing?view=aspnetcore-3.0

{BACK_TO_TOP}

=== [x] *Docker* : libérer la *mémoire*

On peut facilement *être saturé de plusieurs dizaines de Go* de données créées par Docker.

==== *Astuce 1* : Supprimer les données non utilisées

Dans un premier temps, il est possible de *supprimer tout ce qui n'est plus utilisé par Docker* :

```
$ docker system prune
```

[NOTE]
====
https://docs.docker.com/engine/reference/commandline/system_prune/ : +
"Remove all unused containers, networks, images (both dangling and unreferenced), and optionally, volumes."
====

TIP: Retrouvez dans la doc d'autres commandes de suppression sur <<makefile>>.

{BACK_TO_TOP}

==== *Astuce 2* : Changer le dossier de travail de *Docker*

Pour une gestion à long terme, il est préférable *d'orienter Docker vers un espace de travail plus volumineux* sur votre machine,
avec le fichier de configuration `daemon.json`.

===== 1) *Stopper Docker* :

```
$ sudo service docker stop
```

===== 2) *Créer* le nouveau dossier de destination :

```
$ sudo mkdir /data/home/jprivet/docker
```

===== 3) *Vérifier* si `daemon.json` existe :

```
$ ls /etc/docker
key.json
```

===== 4) Si `daemon.json` n'existe pas, *le créer* :

```
$ sudo touch /etc/docker/daemon.json
```

===== 4 bis) *Injecter* l'option `"data-root": "/data/home/jprivet/docker"` dans le nouveau fichier `daemon.json` :

```
$ sudo -- sh -c "echo '{\"data-root\": \"/data/home/jprivet/docker\"}' >> /etc/docker/daemon.json"
```

[NOTE]
====
Si le fichier `daemon.json` existe déjà, *le modifier* directement :

```
$ sudo vim /etc/docker/daemon.json
```
====

===== 5) *Vérifier* le contenu du fichier `daemon.json` :

```
$ cat /etc/docker/daemon.json
{"data-root": "/data/home/jprivet/docker"}

```

===== 6) *Redémarrer Docker* :

```
$ sudo service docker start
```

Au prochain `$ docker-compose up`, les éléments seront créés dans le nouveau dossier `/data/home/jprivet/docker`.

{BACK_TO_TOP}

==== Ressources

. https://medium.com/developer-space/how-to-change-docker-data-folder-configuration-33d372669056
. https://docs.docker.com/engine/reference/commandline/dockerd/
. https://docs.docker.com/engine/reference/commandline/system_prune/

{BACK_TO_TOP}

=== [!] *Fixtures* : dans son test, comment en récupérer une avec son *id* ?

==== Exemple : récupérer le slug d'une news

Nous avons des fixtures dans le fichier {uri-rel-file-base}fixtures/news.yaml[] suivant :

```yaml
App\Entity\News:
  news_published_1:
    slug: 'week-601'
    title: 'A week of symfony #601 (2-8 July 2018)'
    body: '...'
  news_published_2:
    slug: 'symfony-live-usa-2018'
    title: 'Join us at SymfonyLive USA 2018!'
    body: '...'
  news_not_published_1:
    slug: 'not-published-news'
    title: 'Not published news'
    body: '...'
```

Dans le test {uri-rel-file-base}tests/Functional/Repository/NewsRepositoryTest.php[], il est possible d'avoir *accès par défaut à la liste des fixtures* chargées
et de pointer la news `news_published_1` :

```php
class NewsRepositoryTest extends RepositoryWebTestCase
{
    public function testFindOnePublishedBySlug()
    {
        // Arrange
        $news = self::$fixtures['news_published_1']; // (1)
        $slug = $news->getSlug();

        // Act
        $news = $this->repository->findOnePublishedBySlug($slug);

        // Assert
        $this->assertInstanceOf(News::class, $news);
        $this->assertSame($slug, $news->getSlug());
    }
}
```
<1> Accès par défaut au tableau des fixtures (sans typage de la donnée récupérée).

Le fichier `NewsRepositoryTest` exploite {uri-rel-file-base}tests/Shared/Fixtures/FixturesDecorator.php[],
ce qui permet de récupérer une fixture typée, et *d'activer l'autocomplétion de votre IDE* :

```php
class NewsRepositoryTest extends RepositoryWebTestCase
{
    public function testFindOnePublishedBySlug()
    {
        // Arrange
        $news = $this->fixtures()->news('news_published_1'); // (1)
        $slug = $news->getSlug();

        /* ... */
    }
}
```
<1> Récupération d'une fixture typée.

{BACK_TO_TOP}

=== [ ] *Symfony Panther* : activer la *couverture de code* [[panther-code-coverage]]

Voir aussi dans la doc <<panther-bases>>

{BACK_TO_TOP}

=== [x] *Repositories & QueryBuilder* : organisez la construction de vos *requêtes*

==== Présentation

Au cours du https://paris2019.live.symfony.com/[Symfony Live Paris 2019], https://twitter.com/romaricdrigon[@romaricdrigon] présentait quelques astuces pour organiser les repositories.

==== Exemple

Ici, j'utilise pour mon fichier {uri-rel-file-base}src/Repository/NewsRepository.php[] son https://speakerdeck.com/romaricdrigon/doctrine-en-dehors-des-sentiers-battus-7020e5ed-33a1-4f1d-9bf1-ea9062bdf5ed?slide=33[Astuce 3 : organiser ses repositories...] :
je découpe mon `QueryBuilder` *en sous-portions*.

Ces portions peuvent ensuite *être réexploitées dans d'autres méthodes* :

```php
class NewsRepository extends AbstractRepository implements NewsRepositoryInterface
{
    // ...

    public function findAllPublished(): array
    {
        $queryBuilder = $this->createQueryBuilder(self::ALIAS);
        self::isPublished($queryBuilder); // (1)

        return $queryBuilder->getQuery()->getResult();
    }

    public function findOnePublishedBySlug(string $slug): ?News
    {
        $queryBuilder = $this->createQueryBuilder(self::ALIAS);
        self::isPublished($queryBuilder); // (1)
        self::withSlug($queryBuilder, $slug);
        // ...
    }

    private static function isPublished(QueryBuilder $queryBuilder): void
    {
        $queryBuilder
            ->andWhere(self::ALIAS . '.published = :published')
            ->setParameter('published', self::IS_PUBLISHED);
    }

    // withSlug(), ...
}
```
<1> Surcharge de `$queryBuilder` avec la méthode `isPublished()`.

==== Fichier

. {uri-rel-file-base}src/Repository/NewsRepository.php[]

==== Ressources

. https://github.com/SymfonyLive/paris-2019-talks
. https://speakerdeck.com/romaricdrigon/doctrine-en-dehors-des-sentiers-battus-7020e5ed-33a1-4f1d-9bf1-ea9062bdf5ed?slide=33

{BACK_TO_TOP}

== Autres ressources

=== Symfony

* https://symfony.com/doc/current/best_practices.html#infrastructure-related-configuration
* https://github.com/symfony/demo
* http://fabien.potencier.org/symfony4-best-practices.html

=== Docker

* https://gist.github.com/bastman/5b57ddb3c11942094f8d0a97d461b430

=== Badges

. https://shields.io/

{BACK_TO_TOP}

== Licence

{uri-repo} est publié sous {uri-license}[licence MIT].

{BACK_TO_TOP}
