// settings:

:toc: macro
:toc-title: Sommaire
:toclevels: 3
:numbered:

ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// variables:

:uri-org: https://github.com/jprivet-dev
:uri-repo: {uri-org}/symfony-tdd

:uri-rel-file-base: link:
:uri-rel-tree-base: link:
ifdef::env-site,env-yard[]
:uri-rel-file-base: {uri-repo}/blob/master/
:uri-rel-tree-base: {uri-repo}/tree/master/
endif::[]

:uri-license: {uri-rel-file-base}LICENSE

:BACK_TO_TOP_TARGET: top-target
:BACK_TO_TOP_LABEL: ⬆ Retour au sommaire
:BACK_TO_TOP: <<{BACK_TO_TOP_TARGET},{BACK_TO_TOP_LABEL}>>

[#{BACK_TO_TOP_TARGET}]
= Symfony 4 & TDD (Workshop)

|===
| Branch 3+| Status

| https://github.com/jprivet-dev/symfony-tdd[master]
| image:https://travis-ci.org/jprivet-dev/symfony-tdd.svg?branch=master["Build Status", link="https://travis-ci.org/jprivet-dev/symfony-tdd"]
| image:https://coveralls.io/repos/github/jprivet-dev/symfony-tdd/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/github/jprivet-dev/symfony-tdd?branch=master"]
| image:https://api.codacy.com/project/badge/Grade/d83935eebccc4610870a0b52039914f3?branch=master["Codacy code quality", link="https://www.codacy.com/manual/jprivet-dev/symfony-tdd?utm_source=github.com&utm_medium=referral&utm_content=jprivet-dev/symfony-tdd&utm_campaign=Badge_Grade"]

| https://github.com/jprivet-dev/symfony-tdd/tree/dev[dev]
| image:https://travis-ci.org/jprivet-dev/symfony-tdd.svg?branch=dev["Build Status", link="https://travis-ci.org/jprivet-dev/symfony-tdd"]
| image:https://coveralls.io/repos/github/jprivet-dev/symfony-tdd/badge.svg?branch=dev["Coverage Status", link="https://coveralls.io/github/jprivet-dev/symfony-tdd?branch=dev"]
| image:https://api.codacy.com/project/badge/Grade/d83935eebccc4610870a0b52039914f3?branch=dev["Codacy code quality", link="https://www.codacy.com/manual/jprivet-dev/symfony-tdd?utm_source=github.com&utm_medium=referral&utm_content=jprivet-dev/symfony-tdd&utm_campaign=Badge_Grade"]
|===

toc::[]

== Présentation

Ce dépôt *Git*  fraîchement créé est un atelier où je concentre, teste et partage des cas pratiques rencontrés (projets clients, R&D, ...) autour des *tests automatiques*, du *TDD* (Test-Driven Development) et du framework *Symfony*.

J'ai démarré cet atelier _dockerisé_ à partir du dépôt https://github.com/dunglas/symfony-docker de  https://dunglas.fr/[Kevin Dunglas].

== Prérequis technique : avoir *Docker CE* et *Docker Compose* installés

* https://docs.docker.com/install/
* https://docs.docker.com/compose/install/

{BACK_TO_TOP}

== Le projet

=== Le récupérer

```sh
$ git clone git@github.com:jprivet-dev/symfony-tdd.git
```
=== Le démarrer

```sh
$ cd symfony-tdd
$ make start
...
...
...
READY!
Open http://localhost/
```

[TIP]
====
Si vous n'avez pas l'outil https://www.gnu.org/software/make/[GNU Make] disponible, démarrer avec la commande  suivante :

```sh
$ docker-compose up -d
```
====

=== Accéder au site

Aller sur https://localhost.

{BACK_TO_TOP}

== *Makefile* : les commandes disponibles de ce projet

Si vous avez l'outil https://www.gnu.org/software/make/[GNU Make] disponible sur votre poste,
affichez toutes les commandes avec la ligne suivante :

```sh
$ make
```

Vous retrouverez toutes les commandes suivantes :

```
PROJECT
-------

 start                          Start the project
 stop                           Stop the project
 tests                          Launch all tests

SYMFONY
-------

 symfony.cc                     Symfony : clear cache (current env)
 symfony.ccp                    Symfony : clear cache (prod)
 symfony.routes                 Symfony : displays current routes

PHPUNIT
-------

 phpunit                        PHPUnit: launch all tests (unit, functional, ...)
 phpunit.coverage               PHPUnit: generate code coverage report in HTML format
 phpunit.coverage.clover        PHPUnit: generate code clover style coverage report
 phpunit.unit                   PHPUnit: launch unit tests
 phpunit.unit.coverage          PHPUnit: generate code coverage report in HTML format for unit tests
 phpunit.functional             PHPUnit: launch functional tests with dump
 phpunit.functional.coverage    PHPUnit: generate code coverage report in HTML format for functional tests

 phpunit.watch                  PHPUnit Watcher: rerun automatically tests whenever you change some code. See https://github.com/spatie/phpunit-watcher
 phpunit.watch.unit             PHPUnit Watcher: rerun only unit tests
 phpunit.watch.functional       PHPUnit Watcher: rerun only functional tests

 xdebug.on                      Xdebug: enable the module
 xdebug.off                     Xdebug: disable the module

QUALITY ASSURANCE - STATIC ANALYZERS
------------------------------------

 qa.phpmetrics                  PHPMetrics: provides tons of metric (Complexity / Volume / Object Oriented / Maintainability). See http://www.phpmetrics.org
 qa.codesniffer                 PHP_CodeSniffer: tokenizes PHP, JavaScript and CSS files and detects violations... See https://github.com/squizlabs/PHP_CodeSniffer
 qa.codesniffer.diff            PHP_CodeSniffer: printing a diff report
 qa.codesniffer.fix             PHP_CodeSniffer: fixing errors automatically
 qa.messdetector                PHP Mess Detector: scans PHP source code and looks for potential problems... See http://phpmd.org/
 qa.security.check              Symfony security: check security of your dependencies. See https://security.symfony.com/

DOCKER
------

 docker.start                   Docker: builds, (re)creates, starts, and attaches to containers for a service (detached mode)
 docker.build                   Docker: same `docker.start` command + build images before starting containers
 docker.stop                    Docker: stops running containers without removing them

 docker.env                     Docker: show environment variables
 docker.ip                      Docker: get ip Gateway
 docker.containers              Docker: list containers
 docker.images                  Docker: list images
 docker.networks                Docker: list networks
 docker.logs                    Docker: show logs
 docker.sh                      Docker: sh access
```

{BACK_TO_TOP}

== *PHPUnit* : gérer les tests automatiques PHP

=== Lancer les tests avec *PHPUnit*

Le projet utilise le *PHPUnit Bridge* de *Symfony* (https://symfony.com/doc/current/testing.html).

Lancez tous les tests avec la commande suivante :

```sh
$ make phpunit
...
...
...
Testing
................................                                  32 / 32 (100%)

Time: 483 ms, Memory: 30.00 MB

OK (32 tests, 74 assertions)

```

[TIP]
====
Si vous n'avez pas l'outil https://www.gnu.org/software/make/[GNU Make] disponible, lancer les tests avec la commande  suivante :

```sh
$ docker-compose exec app ./vendor/bin/simple-phpunit
```
====

{BACK_TO_TOP}

=== *PHPUnit Watcher* : relance automatiquement des tests après modification d'un fichier

Le projet utilise *PHPUnit Watcher* (https://github.com/spatie/phpunit-watcher) que vous pouvez lancer avec la commande suivante :

```sh
$ make phpunit.watch
```

[TIP]
====
Si vous n'avez pas l'outil https://www.gnu.org/software/make/[GNU Make] disponible, lancer le watcher avec la commande  suivante :

```sh
$ docker-compose exec app ./vendor/bin/phpunit-watcher watch
```
====

{BACK_TO_TOP}

=== *Xdebug & Performance* : activation et désactivation à chaud du module

WARNING: *Xdebug* est nécessaire pour générer la couverture de code, mais *augmente considérablement (x10)* le temps d'exécution des tests.

Exécution *avec Xdebug* => *1.52 secondes* :

```sh
$ docker-compose exec app ./vendor/bin/simple-phpunit
stty: standard input
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

Testing
................................                                  32 / 32 (100%)

Time: 1.52 seconds, Memory: 24.00 MB

OK (32 tests, 74 assertions)
```

Exécution *sans Xdebug* => *153 ms* :

```sh
$ docker-compose exec app ./vendor/bin/simple-phpunit
stty: standard input
PHPUnit 8.4.1 by Sebastian Bergmann and contributors.

Error:         No code coverage driver is available

Testing
................................                                  32 / 32 (100%)

Time: 153 ms, Memory: 18.00 MB

OK (32 tests, 74 assertions)
```

[TIP]
====
*Xdebug* peut être activé et désactivé à chaud avec les commandes suivantes :

```sh
$ make xdebug.on
$ make xdebug.off
```
====

*Xdebug* est automatiquement désactivé pour les tests qui ne nécessitent pas de couverture de code et réactivé dans le cas contraire.

Exemple de commandes avec *Xdebug désactivé automatiquement* :

```sh
$ make phpunit
$ make phpunit.unit
$ make phpunit.functional
$ make phpunit.watch
...
```
Exemple de commandes *avec Xdebug activé automatiquement* :

```sh
$ make phpunit.coverage
$ make phpunit.coverage.clover
$ make phpunit.unit.coverage
$ make phpunit.functional.coverage
...
```

{BACK_TO_TOP}

== Sujets traités

=== Injecter un *repository* au lieu de *l'entity manager*

==== Principe

Au lieu d'injecter *l'entity manager* pour récupérer ensuite les *repositories* dont nous avons besoin,
nous pouvons injecter directement les *repositories* concernés.

==== Ressources

* https://matthiasnoback.nl/2014/05/inject-a-repository-instead-of-an-entity-manager/

==== Fichiers

* {uri-rel-file-base}src/Repository/AbstractRepository.php[]
* {uri-rel-file-base}tests/Unit/Repository/AbstractRepositoryTest.php[]

{BACK_TO_TOP}

=== Créer et tester un *repository*

{BACK_TO_TOP}

=== Créer et tester une *classe abstraite*

==== Principe

Le principe est de pouvoir tester unitairement les *méthodes concrètes* d'une classe abstraite.

==== Ressources

* https://phpunit.readthedocs.io/en/8.4/test-doubles.html#mocking-traits-and-abstract-classes
* https://mnapoli.fr/anonymous-classes-in-tests/

==== Fichiers

* {uri-rel-file-base}src/Util/Example/AbstractClassExample.php[]
* {uri-rel-file-base}tests/Unit/Util/Example/AbstractClassExampleTest.php[]

{BACK_TO_TOP}

=== Créer et tester un *custom validator*

==== Principe

Le principe est de gérer et de tester facilement tous les cas limites auxquels pourrait-être
exposé notre *custom validator*.

==== Ressources

* https://symfony.com/doc/current/validation/custom_constraint.html
* https://github.com/symfony/validator/blob/master/Test/ConstraintValidatorTestCase.php
* https://github.com/symfony/validator/blob/master/Tests/Constraints/EmailValidatorTest.php

==== Fichiers

* {uri-rel-file-base}src/Validator/Constraints/Reference.php[]
* {uri-rel-file-base}src/Validator/Constraints/ReferenceValidator.php[]
* {uri-rel-file-base}tests/Unit/Validator/Constraints/ReferenceValidatorTest.php[]

{BACK_TO_TOP}

=== Créer et tester un *custom type*

{BACK_TO_TOP}

=== Créer et tester une *fonction Twig*

{BACK_TO_TOP}

=== Créer un *smoke testing*

{BACK_TO_TOP}

=== Créer, dispatcher et tester un *event*

{BACK_TO_TOP}

=== Mocker le *temps*

{BACK_TO_TOP}

=== Créer et tester une *commande Symfony*

{BACK_TO_TOP}

=== Créer et tester une *requête ajax*

{BACK_TO_TOP}

=== Travailler avec le *workflow component*

{BACK_TO_TOP}

=== Travailler avec le *process bundle*

{BACK_TO_TOP}


=== Travailler avec des *collections d'objets typés*

{BACK_TO_TOP}

=== La performance avec *Doctrine*

{BACK_TO_TOP}

=== Créer et tester un *trait*

{BACK_TO_TOP}

=== Créer et tester un *composant Vue.js*

{BACK_TO_TOP}

=== Créer et tester des *éléments asynchrones PHP*

{BACK_TO_TOP}

== Licence

`symfony-tdd` est publié sous {uri-license}[LICENSE] *MIT*.

{BACK_TO_TOP}
