DC = docker-compose
EXEC = $(DC) exec
APP = $(EXEC) app
PHP = $(APP) php
PHPUNIT = $(APP) ./vendor/bin/simple-phpunit
CODESNIFFER = $(PHP) ./vendor/bin/phpcs
CODESNIFFER_FIX = $(PHP) ./vendor/bin/phpcbf
MESSDETECTOR = $(PHP) ./vendor/bin/phpmd
ARTEFACTS = var/artefacts
XDEBUG_INI = /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
